### ISSUE TITLE
tcc is a result of cellranger count or others

### ISSUE THREAD

**Issue by worker000000** [pachterlab/scRNA-Seq-TCC-prep#7]
Thanks for your great work. I am not very sure the TCC is the result of what, and tcc means this script can distinct different isoforms of a gene in 10x data.  Thanks a lot

**Comment by vasilisNt** [comment]
We introduced TCCs as transcriptomic signatures for scRNA-seq analysis that are able to capture and maintain isoform information for downstream analyses. For more information on TCCs please take a look at https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0970-8. In https://www.nature.com/articles/s41592-018-0303-9 we used TCCs to enable isoform-level gene differential expression from 3'-end 10x data. For a more recent implementation based on BUStools please take a look at https://github.com/BUStools/BUS_notebooks_python/blob/master/dataset-notebooks/10x_t4k_TCC/bus2tcc-gene.ipynb
