### ISSUE TITLE
10X detect and prep pipeline only works for python 2.7

### ISSUE THREAD

**Issue by chanjed** [pachterlab/scRNA-Seq-TCC-prep#8]
Note that the pipeline only works for python 2.x and not python 3.x. Hoping this saves other people a bit of time.

**Comment by vasilisNt** [comment]
Thank you for pointing that out here. That is true for the old v1 chemistry branch (current master). The updated 10x v2 chemistry branch (10xTCCprep-SC3Pv2: https://github.com/pachterlab/scRNA-Seq-TCC-prep/tree/10xTCCprep-SC3Pv2) should be python 3.x compatible. Please also take a look at https://github.com/BUStools/BUS_notebooks_python for a more recent workflow based on the BUS file format (e.g., https://github.com/BUStools/BUS_notebooks_python/blob/master/dataset-notebooks/10x_t4k_TCC/bus2tcc-gene.ipynb). Hope this helps.
